"""empty message

Revision ID: 874a2532e44b
Revises: eff3f11bc100
Create Date: 2020-11-21 20:32:11.347681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874a2532e44b'
down_revision = 'eff3f11bc100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
