"""empty message

Revision ID: 95fd2e878744
Revises: f40d5280512c
Create Date: 2020-11-21 22:54:11.118581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95fd2e878744'
down_revision = 'f40d5280512c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_projects', 'status',
               existing_type=postgresql.ENUM('pending', 'active', name='userprojectstatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_projects', 'status',
               existing_type=postgresql.ENUM('pending', 'active', name='userprojectstatusenum'),
               nullable=True)
    # ### end Alembic commands ###
