"""empty message

Revision ID: e9bff56967fe
Revises: 1f2686f764f6
Create Date: 2020-11-21 17:53:47.904812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bff56967fe'
down_revision = '1f2686f764f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_projects_project_id_fkey', 'user_projects', type_='foreignkey')
    op.drop_constraint('user_projects_user_id_fkey', 'user_projects', type_='foreignkey')
    op.create_foreign_key(None, 'user_projects', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.create_foreign_key('user_projects_user_id_fkey', 'user_projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_projects_project_id_fkey', 'user_projects', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
