"""empty message

Revision ID: f272ca0f018d
Revises: 874a2532e44b
Create Date: 2020-11-21 20:35:50.410921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f272ca0f018d'
down_revision = '874a2532e44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user_projects', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'updated_by')
    op.drop_column('tasks', 'updated_by')
    op.drop_column('projects', 'updated_by')
    # ### end Alembic commands ###
